spring.application.name=goTyolo
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gotyolo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sriharsha.mysore}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:meteor@350}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
